# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable-kf6'
    'frameworks/karchive': '@stable-kf6'
    'frameworks/kconfig': '@stable-kf6'
    'frameworks/kcrash': '@stable-kf6'
    'frameworks/ki18n': '@stable-kf6'
    'frameworks/kitemmodels': '@stable-kf6'
    'frameworks/knewstuff': '@stable-kf6'
    'frameworks/kirigami': '@stable-kf6'
