# SPDX-FileCopyrightText: 2024, 2025 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: artikulate
confinement: strict
grade: stable
base: core24
adopt-info: artikulate
apps:
    artikulate:
        extensions:
        - kde-neon-6
        common-id: org.kde.artikulate.desktop
        desktop: usr/share/applications/org.kde.artikulate.desktop
        command: usr/bin/artikulate
        command-chain:
        - bin/artikulate-launch
        - snap/command-chain/desktop-launch6
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.artikulate
        bus: session
parts:
    launchers:
        source: snap/local/launchers
        plugin: dump
        organize:
            '*': bin/
    artikulate:
        parse-info:
        - usr/share/metainfo/org.kde.artikulate.appdata.xml
        plugin: cmake
        source: .
        source-type: local
        cmake-parameters:
        - -DCMAKE_INSTALL_PREFIX=/usr
        - -DCMAKE_BUILD_TYPE=Release
        - -DQT_MAJOR_VERSION=6
        - -DBUILD_WITH_QT6=ON
        - -DBUILD_TESTING=OFF
        - -DCMAKE_INSTALL_SYSCONFDIR=/etc
        - -DCMAKE_INSTALL_LOCALSTATEDIR=/var
        - -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON
        - -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF
        - -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON
        - -DCMAKE_INSTALL_RUNSTATEDIR=/run
        - -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON
        - -DCMAKE_VERBOSE_MAKEFILE=ON
        - -DCMAKE_INSTALL_LIBDIR=lib/$CRAFT_ARCH_TRIPLET
        - --log-level=STATUS
        - -DCMAKE_LIBRARY_PATH=lib/$CRAFT_ARCH_TRIPLET
        prime:
        - -usr/lib/*/cmake/*
        - -usr/include/*
        - -usr/share/ECM/*
        - -usr/share/man/*
        - -usr/share/icons/breeze-dark*
        - -usr/bin/X11
        - -usr/lib/gcc/$SNAPCRAFT_ARCH_TRIPLET/6.0.0
        - -usr/lib/aspell/*
        - -usr/share/lintian
    artikulate-data:
        after:
        - artikulate
        source: https://invent.kde.org/education/artikulate-data.git
        plugin: dump
        organize:
            'courses': usr/share/artikulate/
    cleanup:
        after:
        - artikulate
        plugin: nil
        build-snaps:
        - core24
        - kf6-core24
        override-prime: |
            set -eux
            for snap in "core24" "kf6-core24"; do
                cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
            done


