#ifndef LIBLEARNERPROFILE_EXPORT_H
#define LIBLEARNERPROFILE_EXPORT_H

// needed for KDE_EXPORT and KDE_IMPORT macros
#include <kdemacros.h>

#ifndef LIBLEARNERPROFILE_EXPORT
# if defined(MAKE_LIBLEARNERPROFILE_LIB)
   // We are building this library
#  define LIBLEARNERPROFILE_EXPORT KDE_EXPORT
# else
   // We are using this library
#  define LIBLEARNERPROFILE_EXPORT KDE_IMPORT
# endif
#endif

# ifndef LIBLEARNERPROFILE_EXPORT_DEPRECATED
#  define LIBLEARNERPROFILE_EXPORT_DEPRECATED KDE_DEPRECATED LIBLEARNERPROFILE_EXPORT
# endif

#endif
